package com.subhrodip.uuidv7

import java.time.Instant
import java.util.UUID
import java.util.concurrent.ThreadLocalRandom
import java.util.concurrent.atomic.AtomicLong

/**
 * Generates and inspects UUID version 7 values.
 *
 * `UUIDv7` is a small, thread-safe utility for producing time-ordered UUIDs that follow the UUIDv7
 * layout defined by RFC 9562. Generated identifiers embed the current Unix epoch millisecond in
 * the most significant 48 bits, set the UUID version to `7`, set the IETF/RFC variant bits, and
 * fill the remaining fields with a per-process monotonic sequence plus random data.
 *
 * The generator is optimized for high-throughput identifier generation. It uses [ThreadLocalRandom]
 * for non-blocking random bits and an [AtomicLong] to maintain a packed timestamp/sequence state
 * without global synchronization. This makes it suitable for primary keys, event identifiers, and
 * other sortable IDs in application code.
 *
 * The generated UUIDs are not cryptographic secrets. Do not use them as session tokens, password
 * reset tokens, API keys, authorization credentials, or any value whose security depends on
 * unpredictability.
 *
 * Ordering is monotonic within a single JVM process. No ordering guarantee is provided across
 * different JVM processes, hosts, containers, or clocks.
 */
public object UUIDv7 {
	/**
	 * Version nibble for UUIDv7 in the most significant 64 bits.
	 */
	private const val VERSION_BITS: Long = 0x7000L

	/**
	 * Mask for the 12-bit UUIDv7 `rand_a` field.
	 */
	private const val SEQUENCE_MASK: Long = 0x0FFFL

	/**
	 * Mask for the 62 random bits below the UUID variant field.
	 */
	private const val RANDOM_MASK: Long = 0x3FFFFFFFFFFFFFFFL

	/**
	 * Packed monotonic generation state.
	 *
	 * The upper bits contain the last logical millisecond. The lower 12 bits contain the most recent
	 * `rand_a` sequence value for that logical millisecond.
	 */
	private val lastState = AtomicLong(0)

	/**
	 * Generates a new UUIDv7 value.
	 *
	 * The returned UUID has:
	 *
	 * - a 48-bit Unix epoch millisecond timestamp,
	 * - UUID version `7`,
	 * - a 12-bit per-process monotonic `rand_a` sequence,
	 * - the IETF/RFC UUID variant,
	 * - 62 non-blocking random bits in `rand_b`.
	 *
	 * If more than one UUID is generated in the same millisecond, the `rand_a` sequence is
	 * incremented to preserve local monotonic ordering. If the system clock moves backward, the
	 * generator continues from the previous logical timestamp. If the 12-bit sequence overflows, the
	 * logical timestamp is advanced by one millisecond and the sequence is reset to zero.
	 *
	 * @return a UUIDv7 identifier suitable for sortable application identifiers.
	 */
	@JvmStatic
	public fun generate(): UUID {
		val state = nextState(System.currentTimeMillis())
		val timestamp = state ushr SEQUENCE_BITS
		val sequence = state and SEQUENCE_MASK

		val msb = (timestamp shl TIMESTAMP_SHIFT) or VERSION_BITS or sequence
		val lsb = (ThreadLocalRandom.current().nextLong() and RANDOM_MASK) or Long.MIN_VALUE

		return UUID(msb, lsb)
	}

	/**
	 * Generates a new UUIDv7 value.
	 *
	 * This method is an alias for [generate] and exists to ease migration from existing utilities
	 * that expose a `randomUUID()` method.
	 *
	 * @return a UUIDv7 identifier.
	 */
	@JvmStatic
	public fun randomUUID(): UUID = generate()

	/**
	 * Parses a canonical UUID string and verifies that it is a UUIDv7 value.
	 *
	 * This method is intentionally stricter than [UUID.fromString]. A syntactically valid UUID is
	 * rejected unless it has version `7` and the IETF/RFC variant.
	 *
	 * @param value canonical UUID string to parse.
	 * @return the parsed UUIDv7 value.
	 * @throws IllegalArgumentException if [value] is malformed or is not a UUIDv7 value.
	 * @throws NullPointerException if Java code passes `null`.
	 */
	@JvmStatic
	public fun parse(value: String): UUID {
		val uuid = UUID.fromString(value)
		require(isVersion7(uuid)) { "Not a UUIDv7 value: $value" }
		return uuid
	}

	/**
	 * Returns whether a string is a syntactically valid UUIDv7 value.
	 *
	 * A value is considered valid only when it can be parsed as a UUID and the parsed UUID has
	 * version `7` with the IETF/RFC variant.
	 *
	 * @param value candidate UUID string.
	 * @return `true` when [value] is a UUIDv7 string; otherwise `false`.
	 * @throws NullPointerException if Java code passes `null`.
	 */
	@JvmStatic
	public fun isValid(value: String): Boolean =
		try {
			isVersion7(UUID.fromString(value))
		} catch (_: IllegalArgumentException) {
			false
		}

	/**
	 * Returns whether a UUID has UUIDv7 version and IETF/RFC variant bits.
	 *
	 * This method only checks structural UUID metadata. It does not validate whether the timestamp
	 * is recent, whether the UUID was generated by this library, or whether the random fields have
	 * any particular entropy distribution.
	 *
	 * @param uuid UUID to inspect.
	 * @return `true` when [uuid] has version `7` and variant `2`.
	 * @throws NullPointerException if Java code passes `null`.
	 */
	@JvmStatic
	public fun isVersion7(uuid: UUID): Boolean = uuid.version() == 7 && uuid.variant() == 2

	/**
	 * Extracts the embedded Unix epoch millisecond timestamp from a UUIDv7 value.
	 *
	 * The timestamp occupies the upper 48 bits of the UUID's most significant 64-bit half. The
	 * returned value is expressed in milliseconds since the Unix epoch.
	 *
	 * @param uuid UUIDv7 value to inspect.
	 * @return embedded Unix epoch millisecond timestamp.
	 * @throws IllegalArgumentException if [uuid] is not a UUIDv7 value.
	 * @throws NullPointerException if Java code passes `null`.
	 */
	@JvmStatic
	public fun extractUnixTimestamp(uuid: UUID): Long {
		require(isVersion7(uuid)) { "Not a UUIDv7 value: $uuid" }
		return uuid.mostSignificantBits ushr TIMESTAMP_SHIFT
	}

	/**
	 * Extracts the embedded timestamp from a UUIDv7 value as an [Instant].
	 *
	 * @param uuid UUIDv7 value to inspect.
	 * @return [Instant] represented by the UUIDv7 timestamp field.
	 * @throws IllegalArgumentException if [uuid] is not a UUIDv7 value.
	 * @throws NullPointerException if Java code passes `null`.
	 */
	@JvmStatic
	public fun extractInstant(uuid: UUID): Instant = Instant.ofEpochMilli(extractUnixTimestamp(uuid))

	/**
	 * Computes the next packed timestamp/sequence state for a generation request.
	 *
	 * This method is lock-free and uses compare-and-set retries to keep timestamp and sequence
	 * updates atomic under concurrent generation.
	 *
	 * @param timestamp current wall-clock millisecond.
	 * @return packed state containing logical timestamp and 12-bit sequence.
	 */
	private fun nextState(timestamp: Long): Long {
		while (true) {
			val previous = lastState.get()
			val previousTimestamp = previous ushr SEQUENCE_BITS
			val previousSequence = previous and SEQUENCE_MASK

			val next =
				if (timestamp > previousTimestamp) {
					pack(timestamp, ThreadLocalRandom.current().nextInt(SEQUENCE_BOUND).toLong())
				} else {
					val nextSequence = previousSequence + 1
					if (nextSequence > SEQUENCE_MASK) {
						pack(previousTimestamp + 1, 0)
					} else {
						pack(previousTimestamp, nextSequence)
					}
				}

			if (lastState.compareAndSet(previous, next)) {
				return next
			}
		}
	}

	/**
	 * Packs a logical timestamp and 12-bit sequence into a single state word.
	 *
	 * @param timestamp logical Unix epoch millisecond.
	 * @param sequence 12-bit `rand_a` sequence.
	 * @return packed state value used by [lastState].
	 */
	private fun pack(
		timestamp: Long,
		sequence: Long,
	): Long = (timestamp shl SEQUENCE_BITS) or (sequence and SEQUENCE_MASK)

	/**
	 * Number of bits reserved for the monotonic `rand_a` sequence.
	 */
	private const val SEQUENCE_BITS = 12

	/**
	 * Bit shift from the UUIDv7 timestamp field to the most significant 64-bit UUID half.
	 */
	private const val TIMESTAMP_SHIFT = 16

	/**
	 * Exclusive upper bound for random sequence seeding.
	 */
	private const val SEQUENCE_BOUND = 1 shl SEQUENCE_BITS
}
